::mods_hookExactClass("events/events/dlc4/sled_race_event", function (o) {
	local create = o.create;
	o.create = function () {
		create();
		::Legends.Screens.hook(this, "B", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_143.png[/img]{%sledder% takes the sled from the mountain man.%SPEECH_ON%I\'ll beat ya to them rock dicks in proper time.%SPEECH_OFF%Everyone raises an eyebrow as %they_sledder% sets the sled down. %They_sledder% jacks %their_sledder% boots against its front and tips it toward the edge of the hillside.%SPEECH_ON%Ready when you are.%SPEECH_OFF%The mountain man gives a signal to start the race and the two zip down the snow in an instant. You\'re not sure if your sellsword played cheap, but the mountain man suddenly turns sideways and flips his sled and he goes rolling through the powder in a flail of beard and limbs. %sledder% meanwhile coasts to an easy victory. The company roars to the victory and carry %them_sledder% up the mountain on their shoulders. If the mercenary did cheat it doesn\'t show on the mountain man\'s face, he is just happy to have had raced at all.}";
		});
		::Legends.Screens.hook(this, "C", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_143.png[/img]{%sledder% takes the sled from the mountain man.%SPEECH_ON%I\'ll beat ya to them rock dicks in proper time.%SPEECH_OFF%Everyone raises an eyebrow as %they_sledder% sets the sled down. %They_sledder% jacks %their_sledder% boots against its front and tips it toward the edge of the hillside.%SPEECH_ON%Ready when you are.%SPEECH_OFF%The mountain man gives a signal to start the race and the two zip down the snow in an instant. Rooster tails of powder shower in their wake and it seems like %sledder% is going to win until %they_sledder% angles incorrectly and smashes right into one of the rock cocks. The sled shatters to pieces and the sellsword goes flying over the stone and lands limply into the snow. Laughing, the company rushes to %their_sledder% aid and brings %them_sledder% back to %their_sledder% feet. %They're_sledder% got some raspberries and something is clicking, but %they_sledder%\'ll live. The mountain man cheers.%SPEECH_ON%Ye almost had me, but yer s\'posed to split the dicks, not ride up them!%SPEECH_OFF%This brings your men to their knees in crying laughter.}";
		});
		::Legends.Screens.hook(this, "D", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_08.png[/img]{%fat%, the fattest man in the company, elects to give it a try. You like %their_fat% chances - given %their_fat% weight it\'s likely %they_fat%\'ll blow right down the mountainside. The mountain man readily accepts the challenge, sets the ground rules, and starts the race proper. The two rip through the snow with ease and, just as you thought, the fat man roars through the powder like lightning through a cloud. But %they_fat% doesn\'t seem to slow. %They_fat% plows right between the two cock rocks, signaling %their_fat% win, but %they're_fat% unable to seize the reins or slow down. %They_fat% barrels over an escarpment and that\'s about the last of you see of %them_fat%. The mountain man grimaces and runs toward the hillside.%SPEECH_ON%%They're_fat% alive! Little busted up, but alive!%SPEECH_OFF%Though you\'re mightily concerned, you look back to see that the company whole is doubled over or on their knees choking with laughter.}";
		});
		::Legends.Screens.hook(this, "E", function (_screen) {
			_screen.Text = "[img]gfx/ui/events/event_143.png[/img]{%shortsighted% volunteers to race the mountain man. You are reluctant to allow that, given the sellsword\'s poor eyesight, but %they_blind% is pretty diligent about the matter. As %they_blind% squats on the sled and takes up the reins you can\'t help but notice that %they_blind% is already squinting downhill as though %they_blind% wouldn\'t tell a mountainside from a red barn.%SPEECH_ON%Ready!%SPEECH_OFF%The mountain man sets the rules and starts the race. Almost immediately the shortsighted sellsword veers off course. Thankfully %they're_blind% not even full speed when %they_blind% slams head first into a rock formation. The sled shatters like a tomato against a pillory and the %person_blind% %themselves_blind% pancakes against the stone. You rush to %their_blind% aid and get %them_blind% to %their_blind% feet, but there you find your foot stepping on something metallic. A treasure chest! You tell the company to get the %person_blind% some proper help while you dig out what you can.}";
		});
	}
});
